### ISSUE TITLE
After training is finished for 24 epochs, the evaluation at the end exist in error

### ISSUE THREAD

**Issue by ajayvohra2005** [armandmcqueen/tensorpack-mask-rcnn#32]
```Sun Apr 21 22:23:06 2019[1,0]<stderr>:2019-04-21 22:23:06.226791: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Sun Apr 21 22:23:06 2019[1,0]<stderr>:Traceback (most recent call last):
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/MaskRCNN/train.py", line 660, in <module>
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    launch_train_with_config(traincfg, trainer)
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/tensorpack/train/interface.py", line 94, in launch_train_with_config
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    extra_callbacks=config.extra_callbacks)
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/tensorpack/train/base.py", line 343, in train_with_defaults
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    steps_per_epoch, starting_epoch, max_epoch)
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/tensorpack/train/base.py", line 315, in train
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/tensorpack/utils/argtools.py", line 176, in wrapper
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    return func(*args, **kwargs)
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/tensorpack/train/base.py", line 287, in main_loop
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    self._callbacks.trigger_epoch()
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/tensorpack/callbacks/base.py", line 150, in trigger_epoch
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    self._trigger_epoch()
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/tensorpack/callbacks/group.py", line 97, in _trigger_epoch
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    cb.trigger_epoch()
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/tensorpack/callbacks/base.py", line 150, in trigger_epoch
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    self._trigger_epoch()
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/MaskRCNN/eval.py", line 392, in _trigger_epoch
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    self._eval()
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/MaskRCNN/eval.py", line 385, in _eval
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    all_results, self._eval_dataset, output_file)
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/MaskRCNN/dataset.py", line 279, in eval_or_save_inference_results
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    return COCODetection(cfg.DATA.BASEDIR, dataset).print_coco_metrics(output)
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/tensorpack-mask-rcnn/MaskRCNN/dataset.py", line 57, in print_coco_metrics
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    cocoDt = self.coco.loadRes(json_file)
Sun Apr 21 22:23:06 2019[1,0]<stderr>:  File "/usr/local/lib/python3.6/site-packages/pycocotools/coco.py", line 318, in loadRes
Sun Apr 21 22:23:06 2019[1,0]<stderr>:    if 'caption' in anns[0]:
Sun Apr 21 22:23:06 2019[1,0]<stderr>:IndexError: list index out of range
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun.real detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[21679,1],0]
  Exit code:    1
```

**Comment by armandmcqueen** [comment]
This occurs when accuracy is so poor that there are no predictions above the threshold so the list of results is empty.

It's on our list of issues to fix, but is relatively low priority as it is always a symptom of a larger problem.
